# Generated by Django 4.2.23 on 2025-06-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/hova.jpeg', null=True, upload_to='uploads'),
        ),
    ]
